packages:
  - 'projects/starters/angular'
  - 'projects/starters/angular-legacy'
  - 'projects/starters/buildless'
  - 'projects/starters/lit-library'
  - 'projects/starters/mpa'
  - 'projects/starters/nextjs'
  - 'projects/starters/react'
  - 'projects/starters/scoped-registry'
  - 'projects/starters/solidjs'
  - 'projects/starters/static'
  - 'projects/starters/typescript'
  - 'projects/starters/vue'
  - 'projects/labs/lighthouse'
  - 'projects/pages'
  - 'projects/elements'
  - 'projects/elements-react'
  - 'projects/storybook'
  - 'projects/testing'
  - 'projects/themes'
