packages:
 - 'projects/demos/angular'
 - 'projects/demos/buildless'
 - 'projects/demos/extensions'
 - 'projects/demos/mpa'
 - 'projects/demos/nextjs'
 - 'projects/demos/react'
 - 'projects/demos/typescript'
 - 'projects/demos/vue'
 - 'projects/pages'
 - 'projects/elements'
 - 'projects/elements-react'