extends: substitution
message: Use '%s' instead of '%s'.
level: warning
ignorecase: true
swap:
  web component: Web Component
  web components: Web Components
  style guide: style guide
  dark-mode: dark mode
  light-mode: light mode
  use-case: use case
  use-cases: use cases
  tree shaking: tree-shaking
  CSS variables: CSS custom properties
  CSS variable: CSS custom property
