import Head from 'next/head';
import React from 'react';
import { MlvButton } from '@elements/elements-react/button';
import { MlvAlert } from '@elements/elements-react/alert';
import { MlvDialog } from '@elements/elements-react/dialog';

export default function Home() {
  const [showDialog, setshowDialog] = React.useState(false);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div mlv-layout="column gap:md align:center" style={{ height: '95vh' }}>
        <h1 mlv-text="heading">NextJS</h1>

        <MlvButton onClick={() => setshowDialog(!showDialog)}>greeting</MlvButton>

        <MlvDialog closable modal hidden={!showDialog} onclose={() => setshowDialog(false)}>
          <MlvAlert status="success">hello there</MlvAlert>
        </MlvDialog>
      </div>
    </>
  );
}
