import { GlobalStateService } from '../services/global.service.js';
import { isFocusable } from './focus.js';

/**
 * Preserves visual DOM ordering when using slots within Shadow DOM
 * See additional information/resources on Shadow DOM linear traversal
 * https://nolanlawson.com/2021/02/13/managing-focus-in-the-shadow-dom/
 * https://www.abeautifulsite.net/posts/querying-through-shadow-roots/
 */
 export function getFlatDOMTree(node: Node, depth = 10): HTMLElement[] {
  return (Array.from(getChildren(node)).reduce((prev: any[], next: any) => {
      const nextChild = Array.from(getChildren(next)).map((i: any) => [i, getFlatDOMTree(i, depth)]);
      return [...prev, [next, [...nextChild]]];
    }, []) as any[])
    .flat(depth);
}

export function getChildren(node: any): NodeListOf<HTMLElement> {
  if (node.documentElement) {
    return node.documentElement.children; // root document children
  } else if (node.shadowRoot) {
    return node.shadowRoot.children; // shadow root direct children
  } else if (node.assignedElements) {
    const slotted = node.assignedElements(); // slotted elements
    return slotted.length ? slotted : node.children; // slot fallback
  } else {
    return node.children; // light DOM direct children
  }
}

export function generateId() {
  return `_${Math.random().toString(36).substring(2, 9)}`;
}

export function getAttributeChanges(element: HTMLElement, attr: string, fn: (attrValue: string) => void) {
  fn(element.getAttribute(attr));
  const observer = new MutationObserver(mutations => {
    mutations.forEach(mutation => {
      if (mutation.attributeName === attr) {
        fn((mutation.target as HTMLElement).getAttribute(attr));
      }
    });
  });
  observer.observe(element, { attributes: true, subtree: true });
  return observer;
}

export function getAttributeListChanges(element: HTMLElement, attrs: string[], fn: (mutation: MutationRecord) => void) {
  const observer = new MutationObserver(mutations => {
    mutations.forEach(mutation => {
      if (attrs.includes(mutation.attributeName)) {
        fn(mutation);
      }
    });
  });
  observer.observe(element, { attributes: true, subtree: true });
  return observer;
}

/**
 * Appends styles to the render root of a given element. This is useful for
 * styles that need to be applied outside the scope of the element's shadow
 * root such as UA styles --webkit-* that won't work in a ::slotted selector
 */
export function appendRootNodeStyle(host: HTMLElement, styles: string) {
  const stylesheet = new CSSStyleSheet();
  (stylesheet as any).replaceSync(styles ?? ''); // vitest in coverage mode ignores inlined assets like css and returns undefined
  const root = host.getRootNode() as any;
  if (root.adoptedStyleSheets) {
    root.adoptedStyleSheets = [...Array.from(root.adoptedStyleSheets), stylesheet];
  }
}

/* used for cases of needing to know a property update outside of lit, example a native input value prop change */
export function getElementUpdate(element: HTMLElement, key: string, callback: (value: any) => void) {
  if (element.hasAttribute(key)) {
    callback(element.getAttribute(key));
  } else if ((element as any)[key] !== undefined) {
    callback((element as any)[key]);
  }

  const updatedProp = Object.getOwnPropertyDescriptor(Object.getPrototypeOf(element), key) as any;
  if (updatedProp) {
    try {
      Object.defineProperty(element, key, {
        get: updatedProp.get,
        set: val => {
          callback(val);
          updatedProp.set.call(element, val);
        },
      });
    } catch {
      // try/catch for cases where prop may have already been defined
    }
  }

  return getAttributeChanges(element, key, val => callback(val));
}

export function clickOutsideElementBounds(event: PointerEvent, element: HTMLElement) {
  const { left, right, top, bottom } = element.getBoundingClientRect();
  return event.clientX < left || event.clientX > right || event.clientY < top || event.clientY > bottom;
}

/** parses number out of basic calc generated by the design tokens */
export function parseTokenNumber(value: string) {
  return parseInt(value.includes('calc') ? value.split(' * ')[1].replace('px)', '') : value, 10) || 0;
}

/**
 * Utility for applying mixin recursively to all custom elements, used for scoped element registry polyfills and shims
 */
export function scope(element: any, Mixin: any) {
  return class extends Mixin(element as any) {
    static elementDefinitions = Object.entries({ ...element.elementDefinitions }).reduce((p, [tag, el]) => ({ ...p, [tag]: scope(el, Mixin) }), { })
  };
}

export function define(element: CustomElementConstructor & { metadata: { version: string; tag: string } }, config = { suffix: '' }) {
  const { tag, version } = element.metadata;
  const suffix = config.suffix ? `-${config.suffix}` : '';
  const tagName = `${tag}${suffix}`;
  if (!customElements.get(tagName)) {
    customElements.define(tagName, element);
    GlobalStateService.dispatch('MLV_ELEMENT_DEFINE', { elementRegistry: { [tagName]: version } });
  } else if (GlobalStateService.state.elementRegistry[tagName] !== version && location.hostname === 'localhost') {
    console.warn(`Element ${tagName} version ${version} already defined, please check for duplicate package versions.`);
  }
}

export function isContextMenuClick(event: MouseEvent) {
  return (event.buttons === 2 && !event.ctrlKey) || (event.buttons === 1 && event.ctrlKey);
}

export function getFlattenedFocusableItems(element: Node, depth = 10) {
  return getFlattenedDOMTree(element, depth).filter((e: HTMLElement) => isFocusable(e)) as HTMLElement[];
}

export function getFlattenedDOMTree(node: Node, depth = 10): HTMLElement[] {
  return (Array.from(getChildren(node)).reduce((p: Node[], n: Node) => (
    [...p, [n, [...Array.from(getChildren(n)).map(i => [i, getFlattenedDOMTree(i, depth)])]]]
  ), []) as HTMLElement[]).flat(depth);
}

export function validKeyNavigationCode(e: KeyboardEvent) {
  return (
    e.code === KeynavCode.End ||
    e.code === KeynavCode.Home ||
    e.code === KeynavCode.PageUp ||
    e.code === KeynavCode.PageDown ||
    e.code === KeynavCode.ArrowUp ||
    e.code === KeynavCode.ArrowDown ||
    e.code === KeynavCode.ArrowLeft ||
    e.code === KeynavCode.ArrowRight
  );
}

export enum KeynavCode {
  End = 'End',
  Home = 'Home',
  PageUp = 'PageUp',
  PageDown = 'PageDown',
  ArrowUp = 'ArrowUp',
  ArrowDown = 'ArrowDown',
  ArrowLeft = 'ArrowLeft',
  ArrowRight = 'ArrowRight'
}

export function removeEmptyTextNode(node: Node) {
  if ((node as Text)?.wholeText?.trim() === '') {
    (node as Text).remove();
  }
}

export function scrollBarWidth() {
  const div = document.createElement('div');
  div.style.setProperty('width', '100px');
  div.style.setProperty('height', '100px');
  div.style.setProperty('overflow', 'scroll');
  div.style.setProperty('position', 'absolute');
  div.style.setProperty('top', '-9999px');
  document.body.appendChild(div);
  const width = div.offsetWidth - div.clientWidth;
  document.body.removeChild(div);
  return width;
}

export function hasScrollBar(el: HTMLElement) {
  return !!(el.scrollTop || (++el.scrollTop && el.scrollTop--));
}

export function waitForScrollEnd(element: HTMLElement) {
  let prevFrame = 0;
  let prevX = element.scrollLeft;
  let prevY = element.scrollTop;

  return new Promise(resolve => {
    function tick(frames) {
      if (frames >= 500 || frames - prevFrame > 20) {
        resolve(null);
      } else {
        if (element.scrollTop !== prevX || element.scrollLeft !== prevY) {
          prevFrame = frames;
          prevX = element.scrollTop;
          prevY = element.scrollLeft;
        }
        requestAnimationFrame(tick.bind(null, frames + 1))
      }
    }
    tick(0);
  });
}

export function endOfScrollBox(element: HTMLElement, offset = 0) {
  return element.scrollTop + element.offsetHeight + offset >= element.scrollHeight;
}

export async function openEyeDropper(): Promise<string> {
  return await new (window as any).EyeDropper().open().then(color => color.sRGBHex);
}
