import { GlobalStateService } from '../services/global.service.js';
import { LogService } from '../services/log.service.js';
import { isFocusable } from './focus.js';

/**
 * CustomStateSet Polyfill for :state() syntax downleveled to legacy :--state syntax (Chromium < v123.?)
 * Can be removed once Chromium stable ships stable :state() API by default
 * This import is in this file to ensure it is setup before a define() call
 */
import '@nvidia-elements/core/polyfills/custom-state-set.js';

/**
 * Preserves visual DOM ordering when using slots within Shadow DOM
 * See additional information/resources on Shadow DOM linear traversal
 * https://nolanlawson.com/2021/02/13/managing-focus-in-the-shadow-dom/
 * https://www.abeautifulsite.net/posts/querying-through-shadow-roots/
 */
export function getFlatDOMTree(node: Node, depth = 10): HTMLElement[] {
  return (
    Array.from(getChildren(node)).reduce((prev: any[], next: any) => {
      const nextChild = Array.from(getChildren(next)).map((i: any) => [i, getFlatDOMTree(i, depth)]);
      return [...prev, [next, [...nextChild]]];
    }, []) as any[]
  ).flat(depth);
}

export function getChildren(node: any): NodeListOf<HTMLElement> {
  if (node.documentElement) {
    return node.documentElement.children; // root document children
  } else if (node.shadowRoot) {
    return node.shadowRoot.children; // shadow root direct children
  } else if (node.assignedElements) {
    const slotted = node.assignedElements(); // slotted elements
    return slotted.length ? slotted : node.children; // slot fallback
  } else {
    return node.children; // light DOM direct children
  }
}

export function generateId() {
  return `_${Math.random().toString(36).substring(2, 9)}`;
}

export function getAttributeChanges(element: HTMLElement, attr: string, fn: (attrValue: string) => any) {
  fn(element.getAttribute(attr));
  const observer = new MutationObserver(mutations => {
    mutations.forEach(mutation => {
      if (mutation.attributeName === attr) {
        fn((mutation.target as HTMLElement).getAttribute(attr));
      }
    });
  });
  observer.observe(element, { attributes: true, subtree: true });
  return observer;
}

export function getAttributeListChanges(element: HTMLElement, attrs: string[], fn: (mutation: MutationRecord) => void) {
  const observer = new MutationObserver(mutations => {
    mutations.forEach(mutation => {
      if (attrs.includes(mutation.attributeName)) {
        fn(mutation);
      }
    });
  });
  observer.observe(element, { attributes: true, subtree: true });
  return observer;
}

/**
 * Appends styles to the render root of a given element. This is useful for
 * styles that need to be applied outside the scope of the element's shadow
 * root such as UA styles --webkit-* that won't work in a ::slotted selector
 */
export function appendRootNodeStyle(host: HTMLElement, styles: string) {
  const stylesheet = new CSSStyleSheet();
  (stylesheet as any).replaceSync(styles ?? ''); // vitest in coverage mode ignores inlined assets like css and returns undefined
  const root = host.getRootNode() as any;
  if (root.adoptedStyleSheets) {
    root.adoptedStyleSheets = [...Array.from(root.adoptedStyleSheets), stylesheet];
  }
  return stylesheet;
}

/* used for cases of needing to know a property update outside of lit, example a native input value prop change */
export function getElementUpdate(element: HTMLElement, key: string, callback: (value: any) => void) {
  if (element.hasAttribute(key)) {
    callback(element.getAttribute(key));
  } else if ((element as any)[key] !== undefined) {
    callback((element as any)[key]);
  }

  const updatedProp = Object.getOwnPropertyDescriptor(Object.getPrototypeOf(element), key) as any;
  if (updatedProp) {
    try {
      Object.defineProperty(element, key, {
        get: updatedProp.get,
        set: val => {
          updatedProp.set.call(element, val);
          callback(val);
        }
      });
    } catch {
      // try/catch for cases where prop may have already been defined
    }
  }

  return getAttributeChanges(element, key, val => callback(val));
}

export function clickOutsideElementBounds(event: PointerEvent, element: HTMLElement) {
  const { left, right, top, bottom } = element.getBoundingClientRect();
  return event.clientX < left || event.clientX > right || event.clientY < top || event.clientY > bottom;
}

/** parses number out of basic calc generated by the design tokens */
export function parseTokenNumber(value: string) {
  return parseInt(value.includes('calc') ? value.split('*')[1].replace('px)', '').trim() : value, 10) || 0;
}

/**
 * Utility for applying mixin recursively to all custom elements, used for scoped element registry polyfills and shims
 */
export function scope(element: any, Mixin: any) {
  return class extends Mixin(element) {
    static elementDefinitions = Object.entries({ ...element.elementDefinitions }).reduce(
      (p, [tag, el]) => ({ ...p, [tag]: scope(el, Mixin) }),
      {}
    );
  };
}

export function define(Element: CustomElementConstructor & { metadata: { version: string; tag: string } }) {
  defineInternal(Element, Element.metadata.tag.replace('mlv', 'nve'));
  defineInternal(class extends Element {}, Element.metadata.tag);
}

function defineInternal(element: CustomElementConstructor & { metadata: { version: string } }, tagName: string) {
  const { version } = element.metadata;
  const tag = tagName.replace('nve-', '').replace('nve-', '');
  if (!customElements.get(tagName)) {
    customElements.define(tagName, element);
    GlobalStateService.dispatch('NVE_ELEMENT_DEFINE', { elementRegistry: { [tag]: version } });
  } else if (
    GlobalStateService.state.elementRegistry[tag] !== version &&
    globalThis?.location?.hostname === 'localhost'
  ) {
    console.warn(`Element ${tag} version ${version} already defined, please check for duplicate package versions.`);
  }
}

export function isContextMenuClick(event: MouseEvent) {
  return (event.buttons === 2 && !event.ctrlKey) || (event.buttons === 1 && event.ctrlKey);
}

export function getFlattenedFocusableItems(element: Node, depth = 10) {
  return getFlattenedDOMTree(element, depth).filter((e: HTMLElement) => isFocusable(e)) as HTMLElement[];
}

export function getFlattenedDOMTree(node: Node, depth = 10): HTMLElement[] {
  return (
    Array.from(getChildren(node)).reduce(
      (p: Node[], n: Node) => [...p, [n, [...Array.from(getChildren(n)).map(i => [i, getFlattenedDOMTree(i, depth)])]]],
      []
    ) as HTMLElement[]
  ).flat(depth);
}

export function validKeyNavigationCode(e: KeyboardEvent) {
  return (
    e.code === KeynavCode.End ||
    e.code === KeynavCode.Home ||
    e.code === KeynavCode.PageUp ||
    e.code === KeynavCode.PageDown ||
    e.code === KeynavCode.ArrowUp ||
    e.code === KeynavCode.ArrowDown ||
    e.code === KeynavCode.ArrowLeft ||
    e.code === KeynavCode.ArrowRight
  );
}

export enum KeynavCode {
  End = 'End',
  Home = 'Home',
  PageUp = 'PageUp',
  PageDown = 'PageDown',
  ArrowUp = 'ArrowUp',
  ArrowDown = 'ArrowDown',
  ArrowLeft = 'ArrowLeft',
  ArrowRight = 'ArrowRight'
}

export function removeEmptyTextNode(node: Node) {
  if ((node as Text)?.wholeText?.trim() === '') {
    (node as Text).remove();
  }
}

export function scrollBarWidth() {
  const div = globalThis.document.createElement('div');
  div.style.setProperty('width', '100px');
  div.style.setProperty('height', '100px');
  div.style.setProperty('overflow', 'scroll');
  div.style.setProperty('position', 'absolute');
  div.style.setProperty('top', '-9999px');
  globalThis.document.body.appendChild(div);
  const width = div.offsetWidth - div.clientWidth;
  globalThis.document.body.removeChild(div);
  return width;
}

export function hasScrollBar(el: HTMLElement) {
  return !!(el.scrollTop || (++el.scrollTop && el.scrollTop--));
}

export function hasHorizontalScrollBar(el: HTMLElement) {
  return el.scrollWidth > el.clientWidth;
}

export function endOfScrollBox(element: HTMLElement, offset = 0) {
  return element.scrollTop + element.offsetHeight + offset >= element.scrollHeight;
}

export async function openEyeDropper(): Promise<string> {
  return await new (globalThis as any).EyeDropper().open().then(color => color.sRGBHex);
}

/**
 * provides a object with key/value of the currently applied design tokens
 */
export function getThemeTokens(element = globalThis.document.querySelector(':root')) {
  // default root or provided element
  const styles = getComputedStyle(element);
  let parent = null;

  // check for parent iframe, same domain iframes change how style sheets are accessed
  try {
    parent = Array.from(globalThis.parent.document.styleSheets);
  } catch {
    parent = [];
  }

  return [...parent, ...Array.from(globalThis.document.styleSheets)]
    .reduce(
      (finalArr, sheet) =>
        finalArr.concat(
          [...sheet.cssRules]
            .filter(rule => rule.type === 1)
            .reduce((propValArr, rule) => {
              const props = [...rule.style]
                .filter(p => p.trim().includes('--mlv'))
                .map(propName => [propName.trim(), rule.style.getPropertyValue(propName).trim()]);
              return [...propValArr, ...props];
            }, [])
        ),
      []
    )
    .reduce((p, token) => ({ ...p, [token[0]]: styles.getPropertyValue(token[0]) }), {});
}

export function removeEmptySlotWhitespace(slot: HTMLSlotElement) {
  if (slotContainsOnlyWhitespace(slot)) {
    slot.assignedNodes().forEach((node: any) => node.remove());
  }
}

export function slotContainsOnlyWhitespace(slot: HTMLSlotElement) {
  const hasNoElements = !slot.assignedNodes().find(i => i.nodeType !== Node.TEXT_NODE);
  const hasOnlyEmptyTextNodes = !slot
    .assignedNodes()
    .find(i => i.nodeType === Node.TEXT_NODE && i.textContent.trim() !== '');
  return hasNoElements && hasOnlyEmptyTextNodes;
}

export function applySlotContentStates(slot: HTMLSlotElement, element: HTMLElement & { _internals: ElementInternals }) {
  const nodes = slot.assignedNodes();
  const name = slot.name ?? 'slot';

  if (nodes.length) {
    element._internals.states.add(`--has-${name}`);
  } else {
    element._internals.states.delete(`--has-${name}`);
  }
}

export function validateSlots(host: HTMLElement) {
  if (GlobalStateService.state.env !== 'production') {
    const slots = Array.from(host.shadowRoot.querySelectorAll('slot'));
    const allowed = (host.constructor as any).metadata.children;
    slots.forEach(slot => {
      const invalid = slot.assignedElements().filter(e => !allowed.map(i => i.toUpperCase()).includes(e.tagName));
      if (invalid.length) {
        LogService.warn(
          `Invalid slotted elements detected in ${host.tagName.toLocaleLowerCase()}. Allowed ${allowed.join(', ')}`
        );
      }
    });
  }
}

export function getDisplayValue(option: { label?: string; value?: string }) {
  if (option) {
    return option.label ? option.label : option.value;
  } else {
    return '';
  }
}
