name: Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          lfs: true
      - uses: pnpm/action-setup@v5
        with:
          run_install: false
      - uses: actions/setup-node@v6
        with:
          node-version-file: './.nvmrc'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'
      - uses: google/wireit@setup-github-actions-caching/v2
      - run: pnpm install --frozen-lockfile
      - run: pnpm exec playwright install --with-deps chromium
      - run: PAGES_BASE_URL="/elements/" pnpm run ci && PAGES_BASE_URL="/elements/" node ./projects/internals/ci/cache-validate.js ci
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: projects/pages/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
